### PR TITLE
Add option preserveMediaQueries to complement removeStyleTags

### LINKED ISSUE #3: Option removeStyleTags='keepMediaQueries'
I'm currently using removeStyleTags=false only to maintain media queries in the output. It would make more sense to only include the media queries and not all the CSS that has already been inlined, so I'm considering adding this as an option. 

I'm debating adding a removeStyleTagsExceptMediaQueries as a more selective version of removeStyleTags but am not a big fan of that name or adding another boolean. I think the cleaner way is to have an option that defines what to do with style tags, like removeStyleTags=true|'keepMediaQueries'. Based on the way I read the code right now, making that change would be non-breaking as long as the true value continues to be truthy like it looks now and any new string match could be strict.

Do you have any thoughts on this?

Thanks for maintaining this fork.

### PR DESCRIPTION
**Pull request by jrit**
This adds the option and test coverage to preserve media queries for CSS inside style tags while removing the rest of the styles from the style tag. This is to resolve https://github.com/andrewrk/juice/issues/3

Based on the somewhat scattered state of the test runners, I added the tests where it made sense, so they are run with `node test/run.js` but had to introduce a new path that includes json format options and run through `juice.JuiceContent` instead of just using `juice`. This felt like it set things up best to add additional tests with other options in the future while keeping all existing tests they way were.

### CODE REVIEW

**Comment by andrewrk** [comment]
Looks like the tests didn't pass on Travis.

**Comment by jrit** [comment]
Looks like a line ending issue, that's what I get for using windows. I'll get that updated. See any other issues while I'm fixing that?

**Comment by andrewrk** [comment]
Seems fine to me. Want to update the README to reflect the API you added here? After that I think it should be good to merge and publish.

**Comment by jrit** [comment]
The readme has been updated

**Comment by andrewrk** [comment]
Thanks for the contribution! Released in 0.7.0

**Pull request merged**
