### PR TITLE
add option applyLinksToStyleTags

### LINKED ISSUE #10: Option preserveMediaQueries also for external css files
Option preserveMediaQueries also for external css files. Is that possible or planned in near future?

### PR DESCRIPTION
**Pull request by jrit**
Intended to resolve https://github.com/andrewrk/juice/issues/10

I want to see if this passes on Travis since I'm concerned about the path resolution on Linux. Also needs documentation, which I'll provide.

### CODE REVIEW

**Comment by andrewrk** [comment]
Looks like a release commit got into the branch somehow?

**Comment by jrit** [comment]
Looks like its pulled from your master, not sure why its showing up here though. There is definitely a problem with the path on Linux though so I'll need to fix that before anything gets merged.

**Comment by jrit** [comment]
I'm unsure if my tests are failing because there is actually something wrong, or it has to do with the change to pend from batch in the test runner causing some weirdness. I do think the outstanding issue with the linux paths is fixed in this though.

**Comment by jrit** [comment]
@andrewrk do you have any thoughts on the test failures in this?

**Comment by andrewrk** [comment]
Nope. I have not looked into it at all.

**Comment by jrit** [comment]
Passing, finally.

**Comment by andrewrk** [comment]
Nice. Taking a look

**Comment by andrewrk** [comment]
This looks good. Can you update the README documentation so that users can find out about this feature and how to use it?

**Comment by jrit** [comment]
@andrewrk I updated the readme and also updated the new option to default to true. I'm not sure if this is the best way to add in the feature or not. The behavior of the new option seems more in line with what should have been happening to begin with, so let me know if you have feelings one way or the other about how this should be handled and I can make any final adjustments.

**Comment by jrit** [comment]
@andrewrk just checking if you saw this was ready to go unless you think the options should be merged

**Comment by andrewrk** [comment]
Sorry for the delay. Would you like to be a maintainer of this module, @jrit ?

**Comment by jrit** [comment]
Sure, I'd be happy to be a maintainer. Thanks.

**Comment by andrewrk** [comment]
npm username?

**Comment by jrit** [comment]
also jrit https://www.npmjs.org/~jrit

**Comment by andrewrk** [comment]
Done, thanks for the help.

**Comment by jannisg** [comment]
Was this ever published to NPM?

Been trying to figure out why the `applyLinksToStyleTags` option didn't work in my workflow and upon digging into the juice2 `lib/juice.js` file I noticed all the changes of this merge missing from my fileset.

I have ran `npm cache clean` and reinstalled the module afterwards but still pulling in the old (without `applyLinksToStyleTags` option) code.

**Comment by jrit** [comment]
@jannisg it wasn't, thanks for pointing that out, it is up to date now

**Pull request merged**
